using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Schukin.DataExchangeTC
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.81.0.
    // 

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class Request
    {
        private DateTime _requestDateField;
        private RequestSender _senderField;
        private RequestRecipient _recipientField;
        private RequestRequestData[] _requestDataField;
        private decimal _versionField;

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public DateTime RequestDate
        {
            get
            {
                return _requestDateField;
            }
            set
            {
                _requestDateField = value;
            }
        }

        /// <remarks/>
        public RequestSender Sender
        {
            get
            {
                return _senderField;
            }
            set
            {
                _senderField = value;
            }
        }

        /// <remarks/>
        public RequestRecipient Recipient
        {
            get
            {
                return _recipientField;
            }
            set
            {
                _recipientField = value;
            }
        }

        /// <remarks/>
        [XmlElement("RequestData")]
        public RequestRequestData[] RequestData
        {
            get
            {
                return _requestDataField;
            }
            set
            {
                _requestDataField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute("version")]
        public decimal Version
        {
            get
            {
                return _versionField;
            }
            set
            {
                _versionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class RequestSender
    {
        private string _idField;
        private string _nameField;

        /// <remarks/>
        [XmlElement(DataType = "integer")]
        public string Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class RequestRecipient
    {
        private string _idField;
        private string _nameField;

        /// <remarks/>
        [XmlElement(DataType = "integer")]
        public string Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class RequestRequestData
    {
        private RequestRequestDataPerson _personField;

        /// <remarks/>
        public RequestRequestDataPerson Person
        {
            get
            {
                return _personField;
            }
            set
            {
                _personField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class RequestRequestDataPerson
    {
        private string _snilsField;
        private string _lastNameField;
        private string _firstNameField;
        private string _secondNameField;
        private DateTime _birthDateField;

        /// <remarks/>
        public string Snils
        {
            get
            {
                return _snilsField;
            }
            set
            {
                _snilsField = value;
            }
        }

        /// <remarks/>
        public string LastName
        {
            get
            {
                return _lastNameField;
            }
            set
            {
                _lastNameField = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return _firstNameField;
            }
            set
            {
                _firstNameField = value;
            }
        }

        /// <remarks/>
        public string SecondName
        {
            get
            {
                return _secondNameField;
            }
            set
            {
                _secondNameField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public DateTime BirthDate
        {
            get
            {
                return _birthDateField;
            }
            set
            {
                _birthDateField = value;
            }
        }
    }
}