using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Schukin.DataExchangeTC
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.81.0.
    // 

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class Answer
    {
        private DateTime _requestDateField;
        private DateTime _answerDateField;
        private AnswerSender _senderField;
        private AnswerRecipient _recipientField;
        private AnswerAnswerData[] _answerDataField;
        private decimal _versionField;

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public DateTime RequestDate
        {
            get
            {
                return _requestDateField;
            }
            set
            {
                _requestDateField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public DateTime AnswerDate
        {
            get
            {
                return _answerDateField;
            }
            set
            {
                _answerDateField = value;
            }
        }

        /// <remarks/>
        public AnswerSender Sender
        {
            get
            {
                return _senderField;
            }
            set
            {
                _senderField = value;
            }
        }

        /// <remarks/>
        public AnswerRecipient Recipient
        {
            get
            {
                return _recipientField;
            }
            set
            {
                _recipientField = value;
            }
        }

        /// <remarks/>
        [XmlElement("AnswerData")]
        public AnswerAnswerData[] AnswerData
        {
            get
            {
                return _answerDataField;
            }
            set
            {
                _answerDataField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute("version")]
        public decimal Version
        {
            get
            {
                return _versionField;
            }
            set
            {
                _versionField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class AnswerSender
    {
        private string _idField;
        private string _nameField;

        /// <remarks/>
        [XmlElement(DataType = "integer")]
        public string Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class AnswerRecipient
    {
        private string _idField;
        private string _nameField;

        /// <remarks/>
        [XmlElement(DataType = "integer")]
        public string Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class AnswerAnswerData
    {
        private AnswerAnswerDataPerson _personField;

        /// <remarks/>
        public AnswerAnswerDataPerson Person
        {
            get
            {
                return _personField;
            }
            set
            {
                _personField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class AnswerAnswerDataPerson
    {
        private string _snilsField;
        private string _lastNameField;
        private string _firstNameField;
        private string _secondNameField;
        private DateTime _birthDateField;
        private AnswerAnswerDataPersonPreferentialCategory _preferentialCategoryField;

        /// <remarks/>
        public string Snils
        {
            get
            {
                return _snilsField;
            }
            set
            {
                _snilsField = value;
            }
        }

        /// <remarks/>
        public string LastName
        {
            get
            {
                return _lastNameField;
            }
            set
            {
                _lastNameField = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return _firstNameField;
            }
            set
            {
                _firstNameField = value;
            }
        }

        /// <remarks/>
        public string SecondName
        {
            get
            {
                return _secondNameField;
            }
            set
            {
                _secondNameField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public DateTime BirthDate
        {
            get
            {
                return _birthDateField;
            }
            set
            {
                _birthDateField = value;
            }
        }

        /// <remarks/>
        public AnswerAnswerDataPersonPreferentialCategory PreferentialCategory
        {
            get
            {
                return _preferentialCategoryField;
            }
            set
            {
                _preferentialCategoryField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.6.81.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class AnswerAnswerDataPersonPreferentialCategory
    {
        private string _idField;
        private string _nameField;
        private DateTime _dateToField;
        private bool _dateToFieldSpecified;

        /// <remarks/>
        [XmlElement(DataType = "integer")]
        public string Id
        {
            get
            {
                return _idField;
            }
            set
            {
                _idField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return _nameField;
            }
            set
            {
                _nameField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public DateTime DateTo
        {
            get
            {
                return _dateToField;
            }
            set
            {
                _dateToField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool DateToSpecified
        {
            get
            {
                return _dateToFieldSpecified;
            }
            set
            {
                _dateToFieldSpecified = value;
            }
        }

    }
}